### ISSUE TITLE
Building frontend fails

### ISSUE THREAD

**Issue by ocelik94** [Oisty/Auster#16]
`Could not resolve "./debug/Components.svelte" from "src/App.svelte"
file: /home/ocelik/Projects/projectoc/oisty/auster/web/src/App.svelte
error during build:
RollupError: Could not resolve "./debug/Components.svelte" from "src/App.svelte"
    at error (file:///home/ocelik/Projects/projectoc/oisty/auster/web/node_modules/rollup/dist/es/shared/node-entry.js:2095:30)
    at ModuleLoader.handleInvalidResolvedId (file:///home/ocelik/Projects/projectoc/oisty/auster/web/node_modules/rollup/dist/es/shared/node-entry.js:23594:24)
    at file:///home/ocelik/Projects/projectoc/oisty/auster/web/node_modules/rollup/dist/es/shared/node-entry.js:23556:26
`
The following error occurs when trying to build the frontend with `npm run build`

**Comment by SantaClaas** [comment]
Ah yes the debug folder is ignored, of course, I'm a professional developer 🤡
